controller_manger:
	ros_parameters:
		update_rate: 1000
	arm_controller:
		type: joint_trajectory_controller/JointTrajectoryController
	
	joint_state_broadcaster:
		type: joint_state_broadcaster/JointStateBroadcaster
arm_controller:
	ros_parameters:
		command_interface:
			- position
		state-inttterface:
			- position
			- velocity
		joints:
			- joint_1
			- joint_2
			- joint_3
			- joint_4
			- joint_5
			- joint_6
			- joint_7
